# Generated by Django 5.1.4 on 2024-12-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assignedproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedProject',
        ),
    ]
